### ISSUE TITLE
CSS right panel not positioning correctly

### ISSUE THREAD

**Issue by zoejab** [zoejab/Battleship#1]
@jasonseminara @zhenpanda @amcooper @WilliamfShaw 

Context

When submitting an issue provide some context as to what the problem is. This includes but is not limited to:

What User Story you are currently working on
-basic css

What you are trying to do
-add the right panel (the hits left and boats hit text) to be in line with the board and the left panel so that its not chilling awkwardly on the bottom

Detailed description of the bug or error
right panel isn't aligned

Relevant code/files/errors, screenshots
![screen shot 2015-10-15 at 9 25 54 am](https://cloud.githubusercontent.com/assets/13875115/10514915/c575d72e-731e-11e5-968c-3bde607a91db.png)

What have you tried?
everything. talked to abner and some random guy upstairs yesterday. Tried positioning changes, floating changes, moving the right panel manually within the html document. 

What would you like help with specifically?
moving it up!

**Comment by amcooper** [comment]
@zhenpanda devised a solution. 
1. HTML: Put the right panel inside the container
2. CSS: 
- Give the container a position of relative and a width of 65% (maybe 75% will work too)
- Give the right panel a position of absolute, a top of 0px, a right of 0px, a margin of 0px, and remove the float.
  I think that does it.

A potentially better way to handle this is to use Bootstrap, which we haven't shown you yet, but just getting set up with Bootstrap's column structure is not too hard.

**Comment by zoejab** [comment]
THANK YOU THAT WORKED!
