### ISSUE TITLE
Object issues in order to associate hits wtih certain boats.

### ISSUE THREAD

**Issue by zoejab** [zoejab/Battleship#2]
@jasonseminara @zhenpanda @amcooper @WilliamfShaw 

Context

When submitting an issue provide some context as to what the problem is. This includes but is not limited to:

What User Story you are currently working on
-indicating to the player that they sunk the battle ship or the patrol boat. 

What you are trying to do
when i originally placed my boats on the board i stripped the assigned locations from the objects so now the locations no longer know which object they came from. So now I'm trying to figure out how to re-associate them by converting the numbers into strings while still maintaining them in the object.

Relevant code/files/errors, screenshots
https://github.com/zoejab/Battleship/blob/master/app.js

What have you tried?
looked through some others tic tac toe approaches to try and translate it. Tried to figure out how to continue to grab locations without stripping the object but it is proving unsuccessful. tried to put it through debugger which indicates where i need to change but also i don't know how to convert within the object. 

What would you like help with specifically?
passing object properties through loops without losing sight of all of their properties.

**Comment by amcooper** [comment]
Are we cool? Can I close this one? I'll close it & you can tell me if I should reopen it (if you can't).
