### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sunsheeppoplar** [zoejab/Battleship#4]
Zoe, the game looks good! I was glad to 'hear' your excitement earlier when we talked on Slack. Now that you're finalizing, I just wanted to point out a few small things that you could do to polish your project some more. 
### Assets

One thing to make your repo look a little neater would to be throw all your .png and .jpg files into an assets folder and resource them so that when people are looking around your repo, they can find your js, index, and assets a lot faster!
### README

Another thing you could consider doing is writing some documentation up for this project. Even if it's basic stuff just like walking someone through how to play battleship with some screenshots, I think neatly documented projects are going to be a great help to you later on when you start your job search and when you start presenting your projects to more and more people. Mention when you made the project and for what cause (this class!) and all those types of things. Workflow documentation is always good stuff.

**Comment by zoejab** [comment]
thanks! definitely agree that I wasn't as organized as I could have been for this - but I fixed that up!
